language: haxe
haxe:
  - "4.0.0-rc.1"

before_install:
  - sudo apt-get install -y mono-devel

install:
  - yes | haxelib install test.hxml

script:
  - haxe test.hxml
  - neko out/neko/test.n
  - out/cpp/TestAll
